[package]
name = "bites"
version = "0.0.0"
edition = "2021"
authors = ["bend-n <bend.n@outlook.com>"]
license = "MIT"
description = "bites of tasty numbers"
repository = "https://github.com/bend-n/bites"
exclude = [".gitignore"]
